services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80    
      - 443:443
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./letsencrypt:/etc/letsencrypt"
      - "./www:/var/www/html"
    depends_on:
      - api
      - front
    networks:
      - agent_network

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - "./letsencrypt:/etc/letsencrypt"
      - "./www:/var/www/html"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    networks:
      - agent_network

  api:
    build:
      context: ./sdl-backend-main
      dockerfile: Dockerfile.prod
    image: stone881129/sdl-api:latest
    restart: always
    expose:
      - 3000
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_NAME=sdls_fullstack_postgres1
    volumes:
      - "./sdl-backend-main/daily_file:/sdl-backend-main/daily_file"
    networks:
      - agent_network
    depends_on:
      postgres:
        condition: service_healthy

  front:
    build:
      context: ./sdl-frontend-main
      dockerfile: Dockerfile.prod
    image: stone881129/sdl-front:latest
    restart: always
    expose:
      - 80
    networks:
      - agent_network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    networks:
      - agent_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  agent_network:

volumes:
  postgres_data: 