services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80    # 保留 80 端口用於 HTTP 重定向和 Let's Encrypt 驗證
      - 443:443  # 添加 443 端口用於 HTTPS
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"  # Nginx 配置文件
      - "./letsencrypt:/etc/letsencrypt"      # Let's Encrypt 憑證目錄
      - "./www:/var/www/html"                 # 用於 Let's Encrypt 驗證的靜態文件目錄
    depends_on:
      - api
    networks:
      - agent_network

  # 添加 Certbot 服務來獲取和管理憑證
  certbot:
    image: certbot/certbot
    volumes:
      - "./letsencrypt:/etc/letsencrypt"
      - "./www:/var/www/html"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    networks:
      - agent_network

  api:
    build:
      context: ./sdl-backend-main
      # dockerfile: dockerfile
    image: stone881129/sdl-api:latest     # <--- 加這行
    expose:
      - 3000
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_NAME=sdls_fullstack_postgres1
    volumes:
      - "./sdl-backend-main:/sdl-backend-main"
      - "/sdl-backend-main/node_modules"
      - "./sdl-backend-main/daily_file:/sdl-backend-main/daily_file"
    networks:
      - agent_network
    depends_on:
      postgres:
        condition: service_healthy

  front:
    build:
      context: ./sdl-frontend-main
      # dockerfile: dockerfile
    image: stone881129/sdl-front:latest   # <--- 加這行
    expose:
      - 5173
    networks:
      - agent_network

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - agent_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=wulab@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=ytwu35415
    ports:
      - "5555:80"
    networks:
      - agent_network

networks:
  agent_network:

volumes:
  postgres_data:
